version: '3.4'

services:
  postgres.carsties:
    container_name: postgres.carsties
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw1234
      - POSTGRES_DB=auctions
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postresql/data
      
  mongodb.carsties:
    container_name: mongodb.carsties
    environment:
      - MONGO_INITDB_DATABASE=SearchDb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
      
  rabbitmq.carsties:
    container_name: rabbitmq.carsties
    ports:
      - 5672:5672
      - 15672:15672

  auctionservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - "ConnectionStrings:DefaultConnection=Server=postgres.carsties:5432;User Id=postgres;Password=postgrespw1234;Database=auctions"
      - "RabbitMq:Host=amqp://guest:guest@rabbitmq.carsties:5672"
      - "IdentityServiceUrl=http://identityservice"
      - "Kestrel:Endpoints:Grpc:Protocols=Http2"
      - "Kestrel:Endpoints:Grpc:Url=http://+:7777"
      - "Kestrel:Endpoints:WebApi:Protocols=Http1"
      - "Kestrel:Endpoints:WebApi:Url=http://+:80"
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - postgres.carsties
      - rabbitmq.carsties
      - identityservice

  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnection=Server=postgres.carsties:5432;User Id=postgres;Password=postgrespw1234;Database=identity"
    ports:
      - 5000:80
    depends_on:
      - postgres.carsties

  searchservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:MongoDbConnection=mongodb://mongodb.carsties:27017"
      - "AuctionServiceUrl=http://auctionservice"
      - "RabbitMq:Host=amqp://guest:guest@rabbitmq.carsties:5672"
    ports:
      - 7002:80
    depends_on:
      - mongodb.carsties
      - rabbitmq.carsties

  gatewayservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80

  biddingservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:BidDbConnection=mongodb://mongodb.carsties:27017"
      - "IdentityServiceUrl=http://identityservice"
      - "RabbitMq:Host=amqp://guest:guest@rabbitmq.carsties:5672"
      - "GrpcAuction=http://auctionservice:7777"
    ports:
      - 7003:80
    depends_on:
      - mongodb.carsties
      - rabbitmq.carsties
      - identityservice
      - auctionservice

  notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "RabbitMq:Host=amqp://guest:guest@rabbitmq.carsties:5672"
    ports:
      - 7004:80
    depends_on:
      - rabbitmq.carsties

volumes:
  pgdata:
  mongodata: