version: '3.4'

services:
  postgres.carsties:
    image: postgres
    
  mongodb.carsties:
    image: mongo
  
  rabbitmq.carsties:
    image: rabbitmq:3-management-alpine

  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
